"""Removed Location Column

Revision ID: 3f79e9a2ed82
Revises: f2e935bf918d
Create Date: 2024-09-17 13:39:19.694035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f79e9a2ed82'
down_revision: Union[str, None] = 'f2e935bf918d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('location', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
