"""Added Concert Table

Revision ID: e718b69d77c9
Revises: 3f79e9a2ed82
Create Date: 2024-09-17 15:25:00.014981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e718b69d77c9'
down_revision: Union[str, None] = '3f79e9a2ed82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concerts', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('concerts', sa.Column('date', sa.String(length=50), nullable=False))
    op.drop_column('concerts', 'concert_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concerts', sa.Column('concert_date', sa.DATE(), nullable=True))
    op.drop_column('concerts', 'date')
    op.drop_column('concerts', 'name')
    # ### end Alembic commands ###
